### ISSUE TITLE
including DataCollection in indexed tags causes some files to fail

### ISSUE THREAD

**Issue by colin-combe** [lars-kolbowski/xiSPEC_ms_parser#7]
including DataCollection in the indexed tags causes some files to fail, example: 

ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2017/04/PXD004748/Infected1_R1.mzid

removing it seems to make it work again. Do you get this behaviour aswell? (At the moment I think you have DataCollection in the list of indexed tags.)

Could be a problem with the data rather than the parser - you're call whether to change parser or say file is broken. (I guess it must be passing schema validation from pyteomics?)

There's quite a lot of files with this problem in pride, probably all come from same piece of software

**Comment by lars-kolbowski** [comment]
Thanks for spotting this! Yes it fails when DataCollection doesn't have an id. 
It is also actually the wrong thing to index. What we actually want to index are 'SpectraData' I pushed a fix https://github.com/lars-kolbowski/xiSPEC_ms_parser/commit/657a8d9d41c25a8d6fb2ef2a9b50b94305603a42

Let me know if this improved the situation!

**Comment by colin-combe** [comment]
> Let me know if this improved the situation!

it did
