### ISSUE TITLE
missing scans

### ISSUE THREAD

**Issue by colin-combe** [lars-kolbowski/xiSPEC_ms_parser#9]
i'm seeing a lot of problems with missing scans, some of them look like problems with parser not data. 

e.g. PXD001054, Adult_1.mzid.gz & 0.75 MB & BMD_2013_07_31_Gastro_Adult_1.mgf (assay 37695)

It gets most scans but complains 6838 is missing. I get same behaviour on spectrumviewer.org and with my variant of parser.

But it looks like scan 6838 is there? (Checked by searching ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2014/09/PXD001054/BMD_2013_07_31_Gastro_Adult_1.mgf for "=6838")

also, if you click 'continue' after error on spectrumviewer.org it looks to me like something's gone bit wrong with data, there are not many annotated fragments. (are you sure its a good idea to give option to continue when something's already gone wrong?)    

I notice yesterday we both added error handling/debugging info at same place in code:
https://github.com/colin-combe/xiSPEC_ms_parser/blob/248e5199ee19d910b1edd4361e83b0f86170fb68/xiSPEC_mgfReader.py#L247
it looks like the info we receive here on start and end position in the file might not be right?

**Comment by colin-combe** [comment]
its to do with new line characters I think.

here:
https://github.com/colin-combe/xiSPEC_ms_parser/blob/248e5199ee19d910b1edd4361e83b0f86170fb68/xiSPEC_mgfReader.py#L174
the value returned by m.start() is out by one for each line ending that has passed

**Comment by colin-combe** [comment]
i can probably fix this tomorrow if you like
(by changing the function get_data_indices so it reads line by line)

**Comment by colin-combe** [comment]
pull #10 contains an altered mgf_reader (xiUI_mgfReader.py) with an alterative approach to reading the mgf file.

Mentioning it for discussion. Its still got problems - I haven't found any case in which that code works.

**Comment by lars-kolbowski** [comment]
I think I found the problem:
the scan 6383 uses scientific syntax for intensity
e.g.:
 `103.05432 2.61326E+06
112.08685 4.29743E+06`

This is not picked up by the regex

**Comment by colin-combe** [comment]
thanks, I hadn't noticed that. Yes, that will cause problems for the regex, but I don't think this is the only source of our problems.

[edit: sorry following is a bit long and difficult to make sense of]

If you get a chance you could check the following, but I'll speak to you when I see you so not urgent:

- scan 6838 doesn't use scientific notation? I checked by searching 'SCANS=6838' in BMD_2013_07_31_Gastro_Adult_1.mgf (data you included looks to be from scan 12592 but guess it was just an example...)

- set a break point on line 158 of xiSPEC_mgfReader.py, just inside the 'while True' loop that reads chunks of mgf file, interested in contents of  spec_positions after one iteration of loop:
![screenshot from 2018-03-08 15-43-31](https://user-images.githubusercontent.com/977607/37160224-a0b0ac7c-22e7-11e8-818c-18a5601e3d8d.png)
you need a editor that lets you go a to specific position in file to check this (GUI emacs lets you do it through its Search menu), but if you do you can see the start positions are drifting out.
The 2500th character of the file is on line 146 - this means that by the time we reach 6th scan (SCANS=2509) the start position is now in the second line of the peak data for that scan.
It looks like this must be mangling the data?

- lastly I checked what happens when we try to get scan 2509. I added
```
         if scan_id == 2509:
            pass
```
into the get_by_id function so I had somewhere to put a breakpoint.
Mysteriously, I got a completely different start position for scan 2509. (2607744?) When you look at the data read from the file it has read scan 6596, from a completely different part of the file.

If you look at spectrumviewer.org, load this data and filter to scan 2509 this confirms the wrong spectrum was retreived somehow. The m/z values for the annotated peaks aren't in spectra 2509 but are in scan 6596

um... message ends...

**Comment by colin-combe** [comment]
so, seems I was wrong about things, the 'drift' looks to be to do with the editor I was using, the results are correct.

The 'mysterious' other scan retrieved was because its (correctly we think) using the index of the spectrum in the file, not the scan number
